### ISSUE TITLE
Requirements and Qt Import

### ISSUE THREAD

**Issue by NickSebClark** [leixingyu/json-viewer#1]
I am a beginner so please be kind ! 

I am having some trouble getting this to run.

Could you provide a requirements.txt file?

I don't know how to get these imports to work:

```
from Qt import QtWidgets, QtCore, QtGui
from Qt import _loadUi
```

I can change 'Qt' to 'PyQt5' to resolve the first line but _loadUI is not a component in PyQt...?

**Comment by leixingyu** [comment]
My bad, Qt is a module that supports all python qt bindings including PyQt5: https://github.com/mottosso/Qt.py

I will update the repo to include Qt as a submodule.

If you wish to use PyQt5:
```
from PyQt5 import uic
uic.loadUi(UIFILE, parent)
```
